//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNet.Scaffolding.MaxWebForms.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebFormsScaffolderDialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebFormsScaffolderDialogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.Scaffolding.MaxWebForms.UI.WebFormsScaffolderDialogResources", typeof(WebFormsScaffolderDialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton_Content {
            get {
                return ResourceManager.GetString("AddButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton_Content {
            get {
                return ResourceManager.GetString("CancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data _context class:.
        /// </summary>
        public static string DataContextTypeLabel_Content {
            get {
                return ResourceManager.GetString("DataContextTypeLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master page placeholder ID:.
        /// </summary>
        public static string DesktopContentPlaceholderIdLabel_Content {
            get {
                return ResourceManager.GetString("DesktopContentPlaceholderIdLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master page:.
        /// </summary>
        public static string DesktopViewsLabel_Content {
            get {
                return ResourceManager.GetString("DesktopViewsLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a master page from the list.
        /// </summary>
        public static string Error_DesktopMasterPageRequired {
            get {
                return ResourceManager.GetString("Error_DesktopMasterPageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid class identifer.
        /// </summary>
        public static string Error_InValidLanguageIndependentIdentifier {
            get {
                return ResourceManager.GetString("Error_InValidLanguageIndependentIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a model class from the list.
        /// </summary>
        public static string Error_ModelTypeRequired {
            get {
                return ResourceManager.GetString("Error_ModelTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the ID of the placeholder control to place the generated content in.
        /// </summary>
        public static string Error_PlaceholderIdRequired {
            get {
                return ResourceManager.GetString("Error_PlaceholderIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model cla_ss:.
        /// </summary>
        public static string ModelTypeLabel_Content {
            get {
                return ResourceManager.GetString("ModelTypeLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over_write existing pages.
        /// </summary>
        public static string OverwriteCheckBox_Content {
            get {
                return ResourceManager.GetString("OverwriteCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Web Forms Pages.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Async Repository Calls.
        /// </summary>
        public static string UseAsyncRepository {
            get {
                return ResourceManager.GetString("UseAsyncRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Client Side Validation.
        /// </summary>
        public static string UseClientSideValidation {
            get {
                return ResourceManager.GetString("UseClientSideValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML5 Validation.
        /// </summary>
        public static string UseHTML5 {
            get {
                return ResourceManager.GetString("UseHTML5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Master Page.
        /// </summary>
        public static string UseMasterPage {
            get {
                return ResourceManager.GetString("UseMasterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Unobtrusive Validation Library.
        /// </summary>
        public static string UseUnobtrusiveJSLibrary {
            get {
                return ResourceManager.GetString("UseUnobtrusiveJSLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Class Name:.
        /// </summary>
        public static string View_Classname {
            get {
                return ResourceManager.GetString("View_Classname", resourceCulture);
            }
        }
    }
}
